name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  SWIFT_VERSION: '5.9'

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Swift version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
    
    - name: Build Release
      run: swift build -c release -v

  test-linux:
    name: Test on Linux (Docker)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t anthropickit:test .
    
    - name: Run tests in Docker
      run: |
        docker run --rm \
          -v $PWD:/workspace \
          -w /workspace \
          swift:${{ env.SWIFT_VERSION }}-jammy \
          swift test -v

  test-linux-native:
    name: Test on Linux (Native)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ env.SWIFT_VERSION }}
    
    - name: Swift version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
    
    - name: Build Release
      run: swift build -c release -v

  documentation:
    name: Build Documentation
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Build Documentation
      run: |
        swift package generate-documentation \
          --target AnthropicKit \
          --output-path ./docs
    
    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: ./docs