name: DocC

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Resolve Dependencies
      run: |
        xcodebuild -resolvePackageDependencies \
          -scheme AnthropicKit \
          -derivedDataPath ~/Developer/Xcode/DerivedData

    - name: Build DocC
      run: |
        xcodebuild docbuild \
          -scheme AnthropicKit \
          -derivedDataPath ~/Developer/Xcode/DerivedData \
          -destination 'platform=macOS' \
          -parallelizeTargets \
          | xcbeautify --renderer github-actions

    - name: Process Archive
      run: |
        ARCHIVE_PATH=$(find ~/Developer/Xcode/DerivedData -name "AnthropicKit.doccarchive" -type d | head -n 1)
        echo "Archive found at: $ARCHIVE_PATH"
        
        xcrun docc process-archive transform-for-static-hosting "$ARCHIVE_PATH" \
          --output-path ./docs \
          --hosting-base-path AnthropicKit

    - name: Create Landing Page
      run: |
        swift Scripts/create_docs_index.swift
        
    - name: List Generated Structure
      run: |
        echo "=== Generated documentation structure ==="
        find ./docs -type f -name "*.html" | grep -E "(tutorial|Tutorial)" | sort || echo "No tutorial files found"
        echo "=== Top-level directories ==="
        ls -la ./docs/
        echo "=== Documentation directory ==="
        ls -la ./docs/documentation/ || echo "No documentation directory"
        echo "=== Checking for tutorials directory ==="
        ls -la ./docs/tutorials/ || echo "No tutorials directory at root"
        ls -la ./docs/documentation/anthropickit/tutorials/ || echo "No tutorials under documentation"

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4