name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${{ github.ref_name }}" \
          --title "${{ github.ref_name }}" \
          --notes "Release ${{ github.ref_name }}"

  build-macos:
    name: Build macOS Binary
    needs: create-release
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
    
    - name: Build Release Binary
      run: |
        swift build -c release
        cp .build/release/anthropic-cli ./anthropic-cli-macos
        chmod +x anthropic-cli-macos
        tar -czf anthropic-cli-macos.tar.gz anthropic-cli-macos
    
    - name: Upload macOS Binary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${{ github.ref_name }}" \
          ./anthropic-cli-macos.tar.gz \
          --clobber

  build-linux:
    name: Build Linux Binary
    needs: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Linux Binary in Docker
      run: |
        docker build -t anthropickit:release .
        docker create --name extract anthropickit:release
        docker cp extract:/app/anthropic-cli ./anthropic-cli-linux
        docker rm extract
        chmod +x anthropic-cli-linux
        tar -czf anthropic-cli-linux.tar.gz anthropic-cli-linux
    
    - name: Upload Linux Binary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload "${{ github.ref_name }}" \
          ./anthropic-cli-linux.tar.gz \
          --clobber